[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
port_baud = 115200

lib_deps =
  marcoschwartz/LiquidCrystal_I2C@^1.1.4
  arduino-libraries/Servo@^1.2.1
  AccelStepper 
